# Generated by Django 4.1.5 on 2023-01-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_offer_product_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(to='product.product'),
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
